-- Stores art created by artists.
-- Each art row belongs to an artist profile.
-- `is_public` lets each owner decide if others can view an item.
create table
    art (
        id bigint generated by default as identity primary key,
        artist_id bigint references artist(id) on delete cascade not null,
        slug text not null unique,
        title text not null,
        description text,
        is_public boolean not null default false,
        instagram_url text
    );

-- Turn on row-level security so policies are enforced.
alter table art enable row level security;

-- Only the signed-in owner can insert art for an artist profile they own.
create policy "Individuals can create art." on art for insert
with
    check (
        exists (
            select 1
            from artist
            where artist.id = art.artist_id
                and artist.user_id = (select auth.uid())
        )
    );

-- Anyone can view public rows, and owners can always view their own rows.
create policy "Users can view own or public art." on art for
select
    using (
        exists (
            select 1
            from artist
            where artist.id = art.artist_id
                and artist.user_id = (select auth.uid())
        )
        or is_public = true
    );

-- Only owners can update their own rows, including visibility.
create policy "Individuals can update their own art." on art for
update using (
    exists (
        select 1
        from artist
        where artist.id = art.artist_id
            and artist.user_id = (select auth.uid())
    )
);

-- Only owners can delete their own rows.
create policy "Individuals can delete their own art." on art for delete using (
    exists (
        select 1
        from artist
        where artist.id = art.artist_id
            and artist.user_id = (select auth.uid())
    )
);