-- Stores artist profile information for users.
-- Each artist is linked to a user account.
create table artist (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null unique,
    slug text not null unique,
    name text not null,
    bio text,
    etsy_link text,
    instagram_link text,
    redbubble_link text,
    website text,
    location text,
    is_public boolean not null default false
);

-- Turn on row-level security so policies are enforced.
alter table artist enable row level security;

-- `user_id unique` enforces one artist profile per authenticated user.

-- Only the signed-in owner can insert a row for their own user_id.
create policy "Individuals can create artist profile." on artist for insert
with
    check (auth.uid () = user_id);


-- Owners can view and update their own artist profile. Anyone can view public profiles.
create policy "Users can view own or public artist profile." on artist for select
    using ((select auth.uid()) = user_id or is_public = true);

create policy "Users can update their own artist profile." on artist for update
    using ((select auth.uid()) = user_id);

-- Only owners can delete their own artist profile.
create policy "Individuals can delete their own artist profile." on artist for delete using ((select auth.uid()) = user_id);
