-- Stores art created by users.
-- `is_public` lets each owner decide if others can view an item.
create table
    art (
        id bigint generated by default as identity primary key,
        user_id uuid references auth.users not null,
        title text not null,
        description text,
        is_public boolean not null default false
    );

-- Turn on row-level security so policies are enforced.
alter table art enable row level security;

-- Only the signed-in owner can insert a row for their own user_id.
create policy "Individuals can create art." on art for insert
with
    check (auth.uid () = user_id);

-- Anyone can view public rows, and owners can always view their own rows.
create policy "Users can view own or public art." on art for
select
    using (
        (
            select
                auth.uid ()
        ) = user_id
        or is_public = true
    );

-- Only owners can update their own rows, including visibility.
create policy "Individuals can update their own art." on art for
update using (
    (
        select
            auth.uid ()
    ) = user_id
);

-- Only owners can delete their own rows.
create policy "Individuals can delete their own art." on art for delete using (
    (
        select
            auth.uid ()
    ) = user_id
);